a = int(input("enter a value :"))
b = int(input("enter a value :"))
print(f"Addition of {a} and {b} is :",a+b)
print(f"Subtraction of {a} and {b} is :",a-b)
print(f"Multiplication of {a} and {b} is :",a*b)
print(f"Division of {a} and {b} is :",a/b)
print(f"Modulus of {a} and {b} is :",a%b)
print(f"Floor Division of {a} and {b} is :",a//b)
print(f"Exponentation of {a} and {b} is :",a**b)
